name: Desplegar Main y Legacy a GitHub Pages

on:
  push:
    branches:
      - main # Se ejecuta cada vez que actualizas main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rama Main
        uses: actions/checkout@v4

      - name: Crear carpeta para Legacy y clonar su contenido
        run: |
          mkdir -p legacy
          git clone --single-branch --branch legacy https://github.com{{ github.repository }}.git legacy-temp
          # Copia el contenido de legacy (evitando la carpeta .git) dentro de /legacy
          rsync -av --exclude='.git' legacy-temp/ legacy/
          rm -rf legacy-temp

      - name: Desplegar todo a GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # Sube todo el directorio raíz, que ahora incluye /legacy
          branch: gh-pages # Crear/actualizar la rama de publicación
