name: Deploy Main and Legacy

on:
  push:
    branches: [ main, legacy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Main Branch to Root
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          enable_jekyll: true

      - name: Deploy Legacy Branch to /legacy/
        if: github.ref == 'refs/heads/legacy'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          destination_dir: legacy
          enable_jekyll: true
